[project]
name = "task-timer"
version = "0.1.0"
description = "Task Timer CLI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
[project.scripts]
task-timer = "task_timer:main"
 
[tool.uv]
package = true